/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  PlaygroundSection,
} from './components/playground/playground';

export namespace Components {
  interface MyPlayground {
    'addSection': (slot: string) => Promise<void>;
  }
  interface PlaygroundSection {
    'slot': string;
  }
}

declare global {


  interface HTMLMyPlaygroundElement extends Components.MyPlayground, HTMLStencilElement {}
  var HTMLMyPlaygroundElement: {
    prototype: HTMLMyPlaygroundElement;
    new (): HTMLMyPlaygroundElement;
  };

  interface HTMLPlaygroundSectionElement extends Components.PlaygroundSection, HTMLStencilElement {}
  var HTMLPlaygroundSectionElement: {
    prototype: HTMLPlaygroundSectionElement;
    new (): HTMLPlaygroundSectionElement;
  };
  interface HTMLElementTagNameMap {
    'my-playground': HTMLMyPlaygroundElement;
    'playground-section': HTMLPlaygroundSectionElement;
  }
}

declare namespace LocalJSX {
  interface MyPlayground extends JSXBase.HTMLAttributes<HTMLMyPlaygroundElement> {}
  interface PlaygroundSection extends JSXBase.HTMLAttributes<HTMLPlaygroundSectionElement> {
    'slot'?: string;
  }

  interface IntrinsicElements {
    'my-playground': MyPlayground;
    'playground-section': PlaygroundSection;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


